### ISSUE TITLE
Need support for Windows

### ISSUE THREAD

**Issue by ashishpatel1992** [informatici/survethi-monitoring-tool#31]
Need support for Windows OS for this project

**Comment by mwithi** [comment]
Hi @ashishpatel1992, thanks a lot for your work!

Are you going to start more PRs related to this issue? 
In which scenario are you using this app?

**Comment by ashishpatel1992** [comment]
I am a University Graduate presently in my final year. Looking forward to contributing to open source work. I found this app as a part of an NGO, which interests me. I am not sure yet if I have anything else to add to this issue. But if I have, I can again reopen this with a comment.

**Comment by mwithi** [comment]
> But if I have, I can again reopen this with a comment.

Totally fine! Thanks!
